### ISSUE TITLE
تداخل این پلاگین با پلاگین پرداخت درون برنامه ای یونیتی

### ISSUE THREAD

**Issue by Hamed1984** [cafebazaar/AuthUnitySdk#1]
سلام
وقتی همزمان از 2 پلاگین 
https://github.com/cafebazaar/AuthUnitySdk/
https://github.com/cafebazaar/CafebazaarUnity
استفاده می کنم این ارور میده
What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.android.vending.billing.IInAppBillingService found in modules BazaarBridge-release-runtime.jar (:BazaarBridge-release:) and BazaarIAB.jar (BazaarIAB.jar)
  Duplicate class com.android.vending.billing.IInAppBillingService$Default found in modules BazaarBridge-release-runtime.jar (:BazaarBridge-release:) and BazaarIAB.jar (BazaarIAB.jar)
  Duplicate class com.android.vending.billing.IInAppBillingService$Stub found in modules BazaarBridge-release-runtime.jar (:BazaarBridge-release:) and BazaarIAB.jar (BazaarIAB.jar)
  Duplicate class com.android.vending.billing.IInAppBillingService$Stub$Proxy found in modules BazaarBridge-release-runtime.jar (:BazaarBridge-release:) and BazaarIAB.jar (BazaarIAB.jar)

لطفاً کدهای مربوط به پرداخت را از داخل پلاگین  حذف کنید.

**Comment by mreram** [comment]
Thanks for report this issue, we will fix it ASAP.

**Comment by Hamed1984** [comment]
حاجی زدی ترکوندیش
![Bug](https://user-images.githubusercontent.com/8165431/124063965-2b5e4c00-da49-11eb-9047-7305ed878571.jpg)

**Comment by mreram** [comment]
با این مشکل در نسخه ریلیز (با پروگارد) مواجه شدید یا دیباگ؟

**Comment by Hamed1984** [comment]
اکی شد
ممنون
